---
- name: "creazione directory per defender"
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: "Copia script defender.py nella VM"
  copy:
    src: "{{ script_src }}"
    dest: "{{ script_dest }}"
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: "Crea file .env con chiave GOOGLE_API"
  copy:
    dest: "{{ project_dir }}/.env"
    content: "api_key={{ gemini_api_key }}"
    owner: vagrant
    group: vagrant
    mode: '0600'
